name: Deploy to EC2

on:
  push:
    branches: [main, stg, dev]
  pull_request:
    branches: [main, stg, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SECRET_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts

    - name: Deploy index.html
      run: |
        ssh ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} sudo mkdir -p /var/www/html
        scp index.html ${{ secrets.USER_NAME}}@${{ secrets.HOST_NAME }}:/home/runner/index.html
        ssh ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} sudo mv ~/index.html /var/www/html/index.html

    - name: Reload Nginx
      run: |
        ssh ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} "sudo systemctl reload nginx"

